# DETECTR 033
To test LOD of cas12a to cleave r17Ar3C

## Formatting to CSV file
Take txt file from plate reader and turn into tidy data format

In [3]:
#import needed libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics

import holoviews as hv
import bokeh
import hvplot.pandas

In [2]:
#read in CSV file
DETECTR_raw = pd.read_csv("../raw_txt_files/191016_DETECTR_033_1.csv", index_col=None, header=None)
DETECTR_raw.loc[DETECTR_raw[0] == "Calculated results: Calc 1: Crosstalk = Crosstalk correction where Label : EC-US-Lum-384 GC edit(1) channel 1", 1] = "crosstalk"
DETECTR_raw.loc[DETECTR_raw[0] == "Results for EC-US-Lum-384 GC edit(1) - channel 0 (CPS)", 1] = "no crosstalk"

DETECTR_raw

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,Plate information,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Plate,Repeat,Barcode,Measured height,Inside temperature at start,Inside temperature at end,Humidity at start,Humidity at end,Ambient temperature at start,Ambient temperature at end,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Background information,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Plate,Label,Result,Signal,Flashes/Time,Meastime,MeasInfo,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,EC-US-Lum-384 GC edit,0,40,1.5,00:00.0,De=USLum Ex=N/A Em=N/A Wdw=N/A (12),NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Calculated results: Calc 1: Crosstalk = Crosst...,crosstalk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
10,A,46099,28512,24485,16333,11549,7603,5331,3749,2912,...,819,869,923,1109,1365,1563,1741,963,973,432
11,B,9445,NaN,6453,NaN,2421,NaN,1152,NaN,653,...,216,NaN,213,NaN,272,NaN,357,NaN,155,NaN
12,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,D,126147,88235,80560,53779,41168,27912,18755,12200,8104,...,2757,957,1077,715,739,749,629,611,661,243
14,E,35251,NaN,26624,NaN,14355,NaN,6744,NaN,3120,...,1120,NaN,1517,NaN,1309,NaN,456,NaN,232,NaN
15,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,G,99712,58653,56968,34173,27507,17829,12856,9552,7979,...,3696,2077,1269,965,827,1739,2355,6709,3688,587
17,H,32843,NaN,22389,NaN,10811,NaN,4947,NaN,2669,...,597,NaN,397,NaN,184,NaN,1963,NaN,531,NaN
18,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,J,24235,67488,29141,211,38749,14568,31669,55824,15675,...,21739,10811,53,1264,43,35,43,51,48,45
20,K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Plate information,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Plate,Repeat,Barcode,Measured height,Inside temperature at start,Inside temperature at end,Humidity at start,Humidity at end,Ambient temperature at start,Ambient temperature at end,...,Kinetics,Measurement date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1,1,NaN,10.98,23.38,23.29,48.5,48.6,23.28,23.18,...,0,10/15/2019 16:07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5736,Notifications for plate 1 repeat 91:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5737,WARNING: Plate height defined in the plate edi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5739,Notifications for plate 1 repeat 92:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5740,WARNING: Plate height defined in the plate edi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5741,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5742,Notifications for plate 1 repeat 93:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5743,WARNING: Plate height defined in the plate edi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5745,Notifications for plate 1 repeat 94:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5746,WARNING: Plate height defined in the plate edi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5748,Notifications for plate 1 repeat 95:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5749,WARNING: Plate height defined in the plate edi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5751,Notifications for plate 1 repeat 96:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5752,WARNING: Plate height defined in the plate edi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5754,Notifications for plate 1 repeat 97:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5755,WARNING: Plate height defined in the plate edi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5757,Notifications for plate 1 repeat 98:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5758,WARNING: Plate height defined in the plate edi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5760,Notifications for plate 1 repeat 99:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5761,WARNING: Plate height defined in the plate edi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5765,Exported with EnVision Workstation version 1.1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
DETECTR_raw = DETECTR_raw.dropna(axis=0,how="all",subset=list(range(1,25
                                                     )))

In [5]:
DETECTR_raw = DETECTR_raw.dropna(axis=0, how="all", subset=[1])

In [6]:
DETECTR_raw.drop(DETECTR_raw.tail(17).index, inplace=True)

In [7]:
DETECTR_raw.reset_index(inplace=True)

In [8]:
DETECTR_raw

,index,0,1,2,3,4,5,6,7,8,...,15,16,17,18,19,20,21,22,23,24
0,1,Plate,Repeat,Barcode,Measured height,Inside temperature at start,Inside temperature at end,Humidity at start,Humidity at end,Ambient temperature at start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,Plate,Label,Result,Signal,Flashes/Time,Meastime,MeasInfo,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6,1,EC-US-Lum-384 GC edit,0,40,1.5,00:00.0,De=USLum Ex=N/A Em=N/A Wdw=N/A (12),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8,Calculated results: Calc 1: Crosstalk = Crosst...,crosstalk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,9,NaN,1,2,3,4,5,6,7,8,...,15,16,17,18,19,20,21,22,23,24
6,10,A,46099,28512,24485,16333,11549,7603,5331,3749,...,819,869,923,1109,1365,1563,1741,963,973,432
7,11,B,9445,NaN,6453,NaN,2421,NaN,1152,NaN,...,216,NaN,213,NaN,272,NaN,357,NaN,155,NaN
8,13,D,126147,88235,80560,53779,41168,27912,18755,12200,...,2757,957,1077,715,739,749,629,611,661,243
9,14,E,35251,NaN,26624,NaN,14355,NaN,6744,NaN,...,1120,NaN,1517,NaN,1309,NaN,456,NaN,232,NaN
10,16,G,99712,58653,56968,34173,27507,17829,12856,9552,...,3696,2077,1269,965,827,1739,2355,6709,3688,587
11,17,H,32843,NaN,22389,NaN,10811,NaN,4947,NaN,...,597,NaN,397,NaN,184,NaN,1963,NaN,531,NaN
12,19,J,24235,67488,29141,211,38749,14568,31669,55824,...,21739,10811,53,1264,43,35,43,51,48,45
13,28,Plate,Repeat,Barcode,Measured height,Inside temperature at start,Inside temperature at end,Humidity at start,Humidity at end,Ambient temperature at start,...,Kinetics,Measurement date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,29,1,1,NaN,10.98,23.38,23.29,48.5,48.6,23.28,...,0,10/15/2019 16:07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,32,Plate,Label,Result,Signal,Flashes/Time,Meastime,MeasInfo,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,33,1,EC-US-Lum-384 GC edit,0,40,1.5,00:00.0,De=USLum Ex=N/A Em=N/A Wdw=N/A (12),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,35,Results for EC-US-Lum-384 GC edit(1) - channel...,no crosstalk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,36,NaN,1,2,3,4,5,6,7,8,...,15,16,17,18,19,20,21,22,23,24
19,37,A,46099,28512,24485,16333,11549,7603,5331,3749,...,819,869,923,1109,1365,1563,1741,963,973,432
20,38,B,9445,NaN,6453,NaN,2421,NaN,1152,NaN,...,216,NaN,213,NaN,272,NaN,357,NaN,155,NaN
21,40,D,126147,88235,80560,53779,41168,27912,18755,12200,...,2757,957,1077,715,739,749,629,611,661,243
22,41,E,35251,NaN,26624,NaN,14355,NaN,6744,NaN,...,1120,NaN,1517,NaN,1309,NaN,456,NaN,232,NaN
23,43,G,99712,58653,56968,34173,27507,17829,12856,9552,...,3696,2077,1269,965,827,1739,2355,6709,3688,587
24,44,H,32843,NaN,22389,NaN,10811,NaN,4947,NaN,...,597,NaN,397,NaN,184,NaN,1963,NaN,531,NaN
25,46,J,24235,67488,29141,211,38749,14568,31669,55824,...,21739,10811,53,1264,43,35,43,51,48,45
26,55,Plate,Repeat,Barcode,Measured height,Inside temperature at start,Inside temperature at end,Humidity at start,Humidity at end,Ambient temperature at start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,56,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,59,Plate,Label,Result,Signal,Flashes/Time,Meastime,MeasInfo,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,60,1,EC-US-Lum-384 GC edit,0,40,1.5,00:00.0,De=USLum Ex=N/A Em=N/A Wdw=N/A (12),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544,5279,E,3680,NaN,2517,NaN,1376,NaN,765,NaN,...,144,NaN,120,NaN,107,NaN,112,NaN,104,NaN
2545,5281,G,11917,7125,5717,3805,2920,2155,1824,1560,...,704,488,440,317,331,651,795,611,499,163
2546,5282,H,2528,NaN,1632,NaN,896,NaN,544,NaN,...,179,NaN,120,NaN,88,NaN,200,NaN,131,NaN
2547,5284,J,7307,27891,10957,67,4939,1445,3509,16091,...,2504,1109,21,131,24,32,29,24,24,29
2548,5293,Plate,Repeat,Barcode,Measured height,Inside temperature at start,Inside temperature at end,Humidity at start,Humidity at end,Ambient temperature at start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2549,5294,1,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2550,5297,Plate,Label,Result,Signal,Flashes/Time,Meastime,MeasInfo,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2551,5298,1,EC-US-Lum-384 GC edit,0,40,1.5,00:00.0,De=USLum Ex=N/A Em=N/A Wdw=N/A (12),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2552,5300,Calculated results: Calc 1: Crosstalk = Crosst...,crosstalk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2553,5301,NaN,1,2,3,4,5,6,7,8,...,15,16,17,18,19,20,21,22,23,24
2554,5302,A,4019,2805,2557,1837,1424,1117,909,763,...,275,312,301,349,435,437,483,315,203,101
2555,5303,B,968,NaN,685,NaN,459,NaN,259,NaN,...,96,NaN,99,NaN,120,NaN,144,NaN,80,NaN
2556,5305,D,13787,9832,8088,5347,4339,2952,2307,1632,...,413,333,336,299,309,283,253,259,235,101
2557,5306,E,3579,NaN,2387,NaN,1323,NaN,776,NaN,...,133,NaN,133,NaN,128,NaN,109,NaN,104,NaN
2558,5308,G,11800,6872,5613,3821,2859,2160,1752,1525,...,621,475,416,323,304,616,755,565,467,152
2559,5309,H,2512,NaN,1635,NaN,880,NaN,485,NaN,...,176,NaN,117,NaN,93,NaN,200,NaN,115,NaN
2560,5311,J,6960,27477,10600,64,4757,1539,3416,15808,...,2352,1133,21,112,21,21,19,27,27,24
2561,5320,Plate,Repeat,Barcode,Measured height,Inside temperature at start,Inside temperature at end,Humidity at start,Humidity at end,Ambient temperature at start,...,Kinetics,Measurement date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2562,5321,1,99,NaN,11.08,24.08,23.98,45,45.9,23.18,...,0,10/16/2019 8:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2563,5324,Plate,Label,Result,Signal,Flashes/Time,Meastime,MeasInfo,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2564,5325,1,EC-US-Lum-384 GC edit,0,40,1.5,00:00.0,De=USLum Ex=N/A Em=N/A Wdw=N/A (12),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2565,5327,Results for EC-US-Lum-384 GC edit(1) - channel...,no crosstalk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2566,5328,NaN,1,2,3,4,5,6,7,8,...,15,16,17,18,19,20,21,22,23,24
2567,5329,A,4019,2805,2557,1837,1424,1117,909,763,...,275,312,301,349,435,437,483,315,203,101
2568,5330,B,968,NaN,685,NaN,459,NaN,259,NaN,...,96,NaN,99,NaN,120,NaN,144,NaN,80,NaN
2569,5332,D,13787,9832,8088,5347,4339,2952,2307,1632,...,413,333,336,299,309,283,253,259,235,101
2570,5333,E,3579,NaN,2387,NaN,1323,NaN,776,NaN,...,133,NaN,133,NaN,128,NaN,109,NaN,104,NaN
2571,5335,G,11800,6872,5613,3821,2859,2160,1752,1525,...,621,475,416,323,304,616,755,565,467,152
2572,5336,H,2512,NaN,1635,NaN,880,NaN,485,NaN,...,176,NaN,117,NaN,93,NaN,200,NaN,115,NaN
2573,5338,J,6960,27477,10600,64,4757,1539,3416,15808,...,2352,1133,21,112,21,21,19,27,27,24

In [ ]:
# #drop unnecessary rows at the end of the csv
# DETECTR_raw = DETECTR_raw.drop(list(range(len(DETECTR_raw)-2, len(DETECTR_raw))), axis=0)

In [ ]:
# #select only the first columns
# DETECTR_raw = DETECTR_raw.iloc[:,0:26]

### number of repeats equals num_plate_reads

In [9]:
#set a variable to identify the number of plate reads
num_plate_reads= 99
# looks for rows below Repeat
# DETECTR_raw.loc[[i+1 for i in DETECTR_raw.loc[DETECTR_raw[1] == 'Repeat'].index], :]

In [10]:
#create a dictionary mapping the row number to a letter for 384 and 96
well_dict_384 = {1:"A",2:"B",3:"C",4:"D",5:"E",6:"F",7:"G",8:"H",9:"I",10:"J",11:"K",12:"L",13:"M",14:"N",15:"O",16:"P"}
well_dict_96 = {1:"A",2:"A",3:"B",4:"B",5:"C",6:"C",7:"D",8:"D",9:"E",10:"E",11:"F",12:"F",13:"G",14:"G",15:"H",16:"H"}

In [25]:
#initialize the cleaned data frame
DETECTR_cleaned = pd.DataFrame(columns = ['time','crosstalk', 'row_384','column_384', 'rfu_value'])
repeat_idx = DETECTR_raw.loc[DETECTR_raw[1] == "Repeat"]
# .index
for idx_raw, idx_cleaned in zip(repeat_idx.index, range(0,len(repeat_idx.index)-1)):
#     print(idx_raw, idx_cleaned)
    curr = repeat_idx.loc[idx_raw, 1]
#     print("curr", curr)
#     raise ValueError
    next_idx = DETECTR_raw.loc[idx_raw+1, 1]
    time = next_idx * 10

    crosstalk_idx = i+4
    possible_crosstalk = DETECTR_raw.loc[idx_raw+4, 1]
    # converting repeat to measureable time

    DETECTR_cleaned[idx_cleaned, 'time'] = time
      
    DETECTR_cleaned[idx_cleaned, 'crosstalk'] = possible_crosstalk
    try:
        for j in list(range(3, 26,2)):
            for k in list(range(idx_raw*16+12, idx_raw*16+16)):
#                 print(k,j)
                subset = dict(
                    zip(
                        ['time','crosstalk', 'row_384','column_384', 'rfu_value'],
                        [time, possible_crosstalk, DETECTR_raw.loc[k%16+1], j-1, ]
                    ) 
                )
                DETECTR_cleaned[idx_cleaned, 'rfu_value'] = DETECTR_raw.loc[k,j+6]
                DETECTR_cleaned[idx_cleaned, 'row_384'] = DETECTR_raw.loc[k%16+1]
                DETECTR_cleaned[idx_cleaned, 'column_384'] = j-1
    except:
        pass
            
            
            
#     DETECTR_cleaned[idx_cleaned, 'row_384'] = DETECTR_raw.loc[idx_raw+6, 1]
#     DETECTR_cleaned[idx_cleaned, 'column_384'] = " ".join(DETECTR_raw.loc[idx_raw+5, 2:26])
#     DETECTR_cleaned[idx_cleaned, 'rfu_value'] = " ".join(DETECTR_raw.loc[idx_raw+5, 2:26])
    # crosstalk?
#     DETECTR_cleaned[i, 'crosstalk'] = 'crosstalk'
#     info_df = DETECTR_raw.loc[curr+5:next_idx]
#     info_df.columns = []
#     print(DETECTR_cleaned.head())
#     raise ValueError
#     print(info_df)

DETECTR_cleaned.head()

,time,crosstalk,row_384,column_384,rfu_value,"(0, time)","(0, crosstalk)","(0, rfu_value)","(0, row_384)","(0, column_384)",...,"(192, time)","(192, crosstalk)","(193, time)","(193, crosstalk)","(194, time)","(194, crosstalk)","(195, time)","(195, crosstalk)","(196, time)","(196, crosstalk)"
index,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33,16,...,97979797979797979797,crosstalk,97979797979797979797,no crosstalk,98989898989898989898,crosstalk,98989898989898989898,no crosstalk,99999999999999999999,crosstalk
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16,...,97979797979797979797,crosstalk,97979797979797979797,no crosstalk,98989898989898989898,crosstalk,98989898989898989898,no crosstalk,99999999999999999999,crosstalk
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EC-US-Lum-384 GC edit,16,...,97979797979797979797,crosstalk,97979797979797979797,no crosstalk,98989898989898989898,crosstalk,98989898989898989898,no crosstalk,99999999999999999999,crosstalk
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,16,...,97979797979797979797,crosstalk,97979797979797979797,no crosstalk,98989898989898989898,crosstalk,98989898989898989898,no crosstalk,99999999999999999999,crosstalk
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,16,...,97979797979797979797,crosstalk,97979797979797979797,no crosstalk,98989898989898989898,crosstalk,98989898989898989898,no crosstalk,99999999999999999999,crosstalk

In [12]:
%debug

> <ipython-input-11-a8084ebe7153>(8)<module>()
      6     curr = repeat_idx.loc[i, 1]
      7     print("curr", curr)
----> 8     raise ValueError
      9     next_idx = repeat_idx.loc[i+1, 1]
     10     print("next index: ", next_idx)

ipdb> repeat_idx.columns
Index(['index',       0,       1,       2,       3,       4,       5,       6,
             7,       8,       9,      10,      11,      12,      13,      14,
            15,      16,      17,      18,      19,      20,      21,      22,
            23,      24],
      dtype='object')
ipdb> repeat_idx.loc[1,1]
*** KeyError: 1
ipdb> repeat_idx.loc[2,1]
*** KeyError: 2
ipdb> repeat_idx.loc[0,1]
'Repeat'
ipdb> repeat_idx
      index      0       1        2                3  \
0         1  Plate  Repeat  Barcode  Measured height
13       28  Plate  Repeat  Barcode  Measured height
26       55  Plate  Repeat  Barcode  Measured height
39       82  Plate  Repeat  Barcode  Measured height
52      109  Plate  Repeat  Barcode  Measured height
65      136  Plate  Repeat  Barcode  Measured height
78      163  Plate  Repeat  Barcode  Measured height
91      190  Plate  Repeat  Barcode  Measured height
104     217  Plate  Repeat  Barcode  Measured height
117     244  Plate  Repeat  Barcode  Measured height
130     271  Plate  Repeat  Barcode  Measured height
143     298  Plate  Repeat  Barcode  Measured height
156     325  Plate  Repeat  Barcode  Measured height
169     352  Plate  Repeat  Barcode  Measured height
182     379  Plate  Repeat  Barcode  Measured height
195     406  Plate  Repeat  Barcode  Measured height
208     433  Plate  Repeat  Barcode  Measured height
221     460  Plate  Repeat  Barcode  Measured height
234     487  Plate  Repeat  Barcode  Measured height
247     514  Plate  Repeat  Barcode  Measured height
260     541  Plate  Repeat  Barcode  Measured height
273     568  Plate  Repeat  Barcode  Measured height
286     595  Plate  Repeat  Barcode  Measured height
299     622  Plate  Repeat  Barcode  Measured height
312     649  Plate  Repeat  Barcode  Measured height
325     676  Plate  Repeat  Barcode  Measured height
338     703  Plate  Repeat  Barcode  Measured height
351     730  Plate  Repeat  Barcode  Measured height
364     757  Plate  Repeat  Barcode  Measured height
377     784  Plate  Repeat  Barcode  Measured height
...     ...    ...     ...      ...              ...
2184   4537  Plate  Repeat  Barcode  Measured height
2197   4564  Plate  Repeat  Barcode  Measured height
2210   4591  Plate  Repeat  Barcode  Measured height
2223   4618  Plate  Repeat  Barcode  Measured height
2236   4645  Plate  Repeat  Barcode  Measured height
2249   4672  Plate  Repeat  Barcode  Measured height
2262   4699  Plate  Repeat  Barcode  Measured height
2275   4726  Plate  Repeat  Barcode  Measured height
2288   4753  Plate  Repeat  Barcode  Measured height
2301   4780  Plate  Repeat  Barcode  Measured height
2314   4807  Plate  Repeat  Barcode  Measured height
2327   4834  Plate  Repeat  Barcode  Measured height
2340   4861  Plate  Repeat  Barcode  Measured height
2353   4888  Plate  Repeat  Barcode  Measured height
2366   4915  Plate  Repeat  Barcode  Measured height
2379   4942  Plate  Repeat  Barcode  Measured height
2392   4969  Plate  Repeat  Barcode  Measured height
2405   4996  Plate  Repeat  Barcode  Measured height
2418   5023  Plate  Repeat  Barcode  Measured height
2431   5050  Plate  Repeat  Barcode  Measured height
2444   5077  Plate  Repeat  Barcode  Measured height
2457   5104  Plate  Repeat  Barcode  Measured height
2470   5131  Plate  Repeat  Barcode  Measured height
2483   5158  Plate  Repeat  Barcode  Measured height
2496   5185  Plate  Repeat  Barcode  Measured height
2509   5212  Plate  Repeat  Barcode  Measured height
2522   5239  Plate  Repeat  Barcode  Measured height
2535   5266  Plate  Repeat  Barcode  Measured height
2548   5293  Plate  Repeat  Barcode  Measured height
2561   5320  Plate  Repeat  Barcode  Measured height

                                4                          5  \
0     Inside temperature at start  Inside temperature at end
13    Inside temperature at start  Inside temperature at end
26    Inside temperature at start  Inside temperature at end
39    Inside temperature at start  Inside temperature at end
52    Inside temperature at start  Inside temperature at end
65    Inside temperature at start  Inside temperature at end
78    Inside temperature at start  Inside temperature at end
91    Inside temperature at start  Inside temperature at end
104   Inside temperature at start  Inside temperature at end
117   Inside temperature at start  Inside temperature at end
130   Inside temperature at start  Inside temperature at end
143   Inside temperature at start  Inside temperature at end
156   Inside temperature at start  Inside temperature at end
169   Inside temperature at start  Inside temperature at end
182   Inside temperature at start  Inside temperature at end
195   Inside temperature at start  Inside temperature at end
208   Inside temperature at start  Inside temperature at end
221   Inside temperature at start  Inside temperature at end
234   Inside temperature at start  Inside temperature at end
247   Inside temperature at start  Inside temperature at end
260   Inside temperature at start  Inside temperature at end
273   Inside temperature at start  Inside temperature at end
286   Inside temperature at start  Inside temperature at end
299   Inside temperature at start  Inside temperature at end
312   Inside temperature at start  Inside temperature at end
325   Inside temperature at start  Inside temperature at end
338   Inside temperature at start  Inside temperature at end
351   Inside temperature at start  Inside temperature at end
364   Inside temperature at start  Inside temperature at end
377   Inside temperature at start  Inside temperature at end
...                           ...                        ...
2184  Inside temperature at start  Inside temperature at end
2197  Inside temperature at start  Inside temperature at end
2210  Inside temperature at start  Inside temperature at end
2223  Inside temperature at start  Inside temperature at end
2236  Inside temperature at start  Inside temperature at end
2249  Inside temperature at start  Inside temperature at end
2262  Inside temperature at start  Inside temperature at end
2275  Inside temperature at start  Inside temperature at end
2288  Inside temperature at start  Inside temperature at end
2301  Inside temperature at start  Inside temperature at end
2314  Inside temperature at start  Inside temperature at end
2327  Inside temperature at start  Inside temperature at end
2340  Inside temperature at start  Inside temperature at end
2353  Inside temperature at start  Inside temperature at end
2366  Inside temperature at start  Inside temperature at end
2379  Inside temperature at start  Inside temperature at end
2392  Inside temperature at start  Inside temperature at end
2405  Inside temperature at start  Inside temperature at end
2418  Inside temperature at start  Inside temperature at end
2431  Inside temperature at start  Inside temperature at end
2444  Inside temperature at start  Inside temperature at end
2457  Inside temperature at start  Inside temperature at end
2470  Inside temperature at start  Inside temperature at end
2483  Inside temperature at start  Inside temperature at end
2496  Inside temperature at start  Inside temperature at end
2509  Inside temperature at start  Inside temperature at end
2522  Inside temperature at start  Inside temperature at end
2535  Inside temperature at start  Inside temperature at end
2548  Inside temperature at start  Inside temperature at end
2561  Inside temperature at start  Inside temperature at end

                      6                7                             8  ...  \
0     Humidity at start  Humidity at end  Ambient temperature at start  ...
13    Humidity at start  Humidity at end  Ambient temperature at start  ...
26    Humidity at start  Humidity at end  Ambient temperature at start  ...
39    Humidity at start  Humidity at end  Ambient temperature at start  ...
52    Humidity at start  Humidity at end  Ambient temperature at start  ...
65    Humidity at start  Humidity at end  Ambient temperature at start  ...
78    Humidity at start  Humidity at end  Ambient temperature at start  ...
91    Humidity at start  Humidity at end  Ambient temperature at start  ...
104   Humidity at start  Humidity at end  Ambient temperature at start  ...
117   Humidity at start  Humidity at end  Ambient temperature at start  ...
130   Humidity at start  Humidity at end  Ambient temperature at start  ...
143   Humidity at start  Humidity at end  Ambient temperature at start  ...
156   Humidity at start  Humidity at end  Ambient temperature at start  ...
169   Humidity at start  Humidity at end  Ambient temperature at start  ...
182   Humidity at start  Humidity at end  Ambient temperature at start  ...
195   Humidity at start  Humidity at end  Ambient temperature at start  ...
208   Humidity at start  Humidity at end  Ambient temperature at start  ...
221   Humidity at start  Humidity at end  Ambient temperature at start  ...
234   Humidity at start  Humidity at end  Ambient temperature at start  ...
247   Humidity at start  Humidity at end  Ambient temperature at start  ...
260   Humidity at start  Humidity at end  Ambient temperature at start  ...
273   Humidity at start  Humidity at end  Ambient temperature at start  ...
286   Humidity at start  Humidity at end  Ambient temperature at start  ...
299   Humidity at start  Humidity at end  Ambient temperature at start  ...
312   Humidity at start  Humidity at end  Ambient temperature at start  ...
325   Humidity at start  Humidity at end  Ambient temperature at start  ...
338   Humidity at start  Humidity at end  Ambient temperature at start  ...
351   Humidity at start  Humidity at end  Ambient temperature at start  ...
364   Humidity at start  Humidity at end  Ambient temperature at start  ...
377   Humidity at start  Humidity at end  Ambient temperature at start  ...
...                 ...              ...                           ...  ...
2184  Humidity at start  Humidity at end  Ambient temperature at start  ...
2197  Humidity at start  Humidity at end  Ambient temperature at start  ...
2210  Humidity at start  Humidity at end  Ambient temperature at start  ...
2223  Humidity at start  Humidity at end  Ambient temperature at start  ...
2236  Humidity at start  Humidity at end  Ambient temperature at start  ...
2249  Humidity at start  Humidity at end  Ambient temperature at start  ...
2262  Humidity at start  Humidity at end  Ambient temperature at start  ...
2275  Humidity at start  Humidity at end  Ambient temperature at start  ...
2288  Humidity at start  Humidity at end  Ambient temperature at start  ...
2301  Humidity at start  Humidity at end  Ambient temperature at start  ...
2314  Humidity at start  Humidity at end  Ambient temperature at start  ...
2327  Humidity at start  Humidity at end  Ambient temperature at start  ...
2340  Humidity at start  Humidity at end  Ambient temperature at start  ...
2353  Humidity at start  Humidity at end  Ambient temperature at start  ...
2366  Humidity at start  Humidity at end  Ambient temperature at start  ...
2379  Humidity at start  Humidity at end  Ambient temperature at start  ...
2392  Humidity at start  Humidity at end  Ambient temperature at start  ...
2405  Humidity at start  Humidity at end  Ambient temperature at start  ...
2418  Humidity at start  Humidity at end  Ambient temperature at start  ...
2431  Humidity at start  Humidity at end  Ambient temperature at start  ...
2444  Humidity at start  Humidity at end  Ambient temperature at start  ...
2457  Humidity at start  Humidity at end  Ambient temperature at start  ...
2470  Humidity at start  Humidity at end  Ambient temperature at start  ...
2483  Humidity at start  Humidity at end  Ambient temperature at start  ...
2496  Humidity at start  Humidity at end  Ambient temperature at start  ...
2509  Humidity at start  Humidity at end  Ambient temperature at start  ...
2522  Humidity at start  Humidity at end  Ambient temperature at start  ...
2535  Humidity at start  Humidity at end  Ambient temperature at start  ...
2548  Humidity at start  Humidity at end  Ambient temperature at start  ...
2561  Humidity at start  Humidity at end  Ambient temperature at start  ...

            15                16   17   18   19   20   21   22   23   24
0          NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
13    Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
26         NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
39    Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
52         NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
65    Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
78         NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
91    Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
104        NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
117   Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
130        NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
143   Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
156        NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
169   Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
182        NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
195   Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
208        NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
221   Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
234        NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
247   Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
260        NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
273   Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
286        NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
299   Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
312        NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
325   Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
338        NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
351   Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
364        NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
377   Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...        ...               ...  ...  ...  ...  ...  ...  ...  ...  ...
2184       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2197  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2210       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2223  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2236       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2249  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2262       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2275  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2288       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2301  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2314       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2327  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2340       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2353  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2366       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2379  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2392       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2405  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2418       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2431  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2444       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2457  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2470       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2483  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2496       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2509  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2522       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2535  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2548       NaN               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2561  Kinetics  Measurement date  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[198 rows x 26 columns]

ipdb> repeat_idx.index
Int64Index([   0,   13,   26,   39,   52,   65,   78,   91,  104,  117,
            ...
            2444, 2457, 2470, 2483, 2496, 2509, 2522, 2535, 2548, 2561],
           dtype='int64', length=198)
ipdb> exit

In [ ]:

### OLD saved for troubleshooting
#initialize the cleaned data frame
DETECTR_cleaned = pd.DataFrame(columns = ['time','crosstalk', 'row_384','column_384', 'rfu_value'])
repeat_idx = DETECTR_raw.loc[DETECTR_raw[1] == "Repeat"]
# .index
for i in range(0, len(repeat_idx.index)-1):
    curr = repeat_idx.loc[i, 1]
    print("curr", curr)
    next_idx = repeat_idx.loc[i+1, 1]
    print("next index: ", next_idx
          
          
#     crosstalk_idx = i+4
    # converting repeat to measureable time
    DETECTR_cleaned[i, 'time'] = DETECTR_raw.loc[i+1, 1] * 10
    # crosstalk?
    DETECTR_cleaned[i, 'crosstalk'] = 'crosstalk'
    info_df = DETECTR_raw.loc[curr+5:next_idx]
#     info_df.columns = []
#     print(DETECTR_cleaned.head())
#     raise ValueError
#     print(info_df)

In [ ]:
repeat_idx = DETECTR_raw.loc[DETECTR_raw[1] == "Repeat"]

In [ ]:
repeat_idx

In [ ]:
#initialize the cleaned data frame
DETECTR_cleaned = pd.DataFrame(columns = ['time','row_384','column_384', 'rfu_value'])

#iterate over each plate to create a dataframe with the correct time, the 384 and 96 position and the RFU_value
for i in list(range(0,num_plate_reads)):
    time = DETECTR_raw.iloc[i*16+12,0]
    for j in list(range(3, 26,2)):
        for k in list(range(i*16+12, i*16+16)):
            rfu_value = DETECTR_raw.loc[k,j]
            row_384 = well_dict_384[k%16+1]
            column_384 = j-1
            #row_96 = well_dict_96[k%16+1]
            #column_96 = j // 2
            DETECTR_cleaned.loc[len(DETECTR_cleaned)] = [time, row_384, column_384,rfu_value]

In [ ]:
#write this file to a CSV
DETECTR_cleaned.to_csv("../tidy_data/DETECTR_029_tidy.csv")

In [ ]:
DETECTR_cleaned = pd.read_csv("../tidy_data/DETECTR_029_tidy.csv")

## Add metadata to data frame

In [ ]:
DETECTR_cleaned=DETECTR_cleaned.assign(input_conc=num_plate_reads*(['10']*2+['5uM']*2+['5']*2+['500nM']*2+['2.5']*2+['50nM']*2+['1.25']*2+['5nM']*2+['0.625']*2+['500pM']*2+['0.3125']*2+['50pM']*2+['0.15625']*2+['5pM']*2+['0.078125']*2+['500fM']*2+['0.0390625']*2+['50fM']*2+['0.0195312']*2+['5fM']*2+['0.0097656']*2+['no_target']*2+['0']*2+['no_cas12a']*2))

In [ ]:
DETECTR_cleaned=DETECTR_cleaned.assign(input_conc_nM=num_plate_reads*(['']*2+['5000']*2+['']*2+['500']*2+['']*2+['50']*2+['']*2+['5']*2+['']*2+['0.5']*2+['']*2+['0.05']*2+['']*2+['0.005']*2+['']*2+['0.0005']*2+['']*2+['0.00005']*2+['']*2+['0.000005']*2+['']*2+['0']*2+['']*2+['0']*2))

In [ ]:
DETECTR_cleaned=DETECTR_cleaned.assign(replicate=num_plate_reads*(24*['a','b']))

In [ ]:
DETECTR_cleaned=DETECTR_cleaned.assign(sample_set=num_plate_reads*(12*['standard','standard','sample','sample']))

In [ ]:
DETECTR_cleaned.head(10)

In [ ]:
DETECTR_cleaned.to_csv("../tidy_data/DETECTR_029_tidy_metadata.csv")

## Filter the data frame
Select only wells we are interested in

In [ ]:
def filter_time(DETECTR_cleaned, time):
    DETECTR = DETECTR_cleaned.loc[DETECTR_cleaned["time"]==time]
    DETECTR = DETECTR.assign(well=(DETECTR['row_384'] + DETECTR['column_384'].map(str)))
    return DETECTR

In [ ]:
def kinetics(DETECTR_cleaned, num_plate_reads):
    DETECTR = DETECTR_cleaned.assign(well=(DETECTR_cleaned['row_384'] + DETECTR_cleaned['column_384'].map(str)))
    return DETECTR

In [ ]:
def standard_curve(DETECTR_cleaned, num_plate_reads):
    DETECTR = DETECTR_cleaned.loc[DETECTR_cleaned['sample_set'].isin(['standard'])]
    DETECTR = DETECTR.assign(standard_conc=DETECTR['input_conc'].map(float))
    return DETECTR

In [ ]:
DETECTR_standard = standard_curve(filter_time(DETECTR_cleaned,'01:00:00'), num_plate_reads)

In [ ]:
DETECTR_standard.hvplot(x='standard_conc', y='rfu_value', kind = 'scatter',hover_cols = ['row_384'])

In [ ]:
#only select rows with the 2 hour time point 
DETECTR_0min = filter_time(DETECTR_cleaned,"00:00:00")

In [ ]:
DETECTR_0min.head(10)

In [ ]:
def get_samples(DETECTR_0min):
    DETECTR_0min=DETECTR_0min[(DETECTR_0min['sample_set'] != 'standard') & (DETECTR_0min['sample_set'] != '')]
    DETECTR_0min.head(10)
    DETECTR_0min=DETECTR_0min.assign(sample_replicate=DETECTR_0min['input_conc']+'_'+DETECTR_0min['replicate'])
    return DETECTR_0min

In [ ]:
DETECTR_0min = get_samples(DETECTR_0min)
DETECTR_0min.head(50)

In [ ]:
DETECTR_0min.hvplot(title = '0 minutes',x='input_conc_nM', by = 'replicate',y= 'rfu_value',hover_cols = ['well'],kind='bar', height=500,rot =90)

In [ ]:
DETECTR_30min = filter_time(DETECTR_cleaned,"00:30:00")

In [ ]:
DETECTR_30min = get_samples(DETECTR_30min)

In [ ]:
DETECTR_30min.hvplot(title = '30 minutes',x='input_conc_nM', by = 'replicate',y= 'rfu_value',hover_cols = ['well'],kind='bar', height=500,rot =90)

In [ ]:
DETECTR_60min = filter_time(DETECTR_cleaned,"01:00:00")

In [ ]:
DETECTR_60min = get_samples(DETECTR_60min)

In [ ]:
DETECTR_60min.hvplot(title = '60 minutes',x='input_conc_nM', by = 'replicate',y= 'rfu_value',hover_cols = ['well'],kind='bar', height=500,rot =90)

In [ ]:
DETECTR_60min.hvplot(title = '60 minutes',x='input_conc_nM', by = 'replicate',y= 'rfu_value',hover_cols = ['well'],kind='scatter', height=500,rot =90)

In [ ]:
DETECTR_kinetics = kinetics(DETECTR_cleaned,num_plate_reads)
#DETECTR_kinetics['rfu_value'] = DETECTR_kinetics['rfu_value'].map(float)

DETECTR_kinetics.hvplot.scatter(x='time',y='rfu_value', by='sample_set',subplots=False,hover_cols = ['well'],rot = 90,height=500)

## Conclusions

NANCY DREW WORKS!! on RNA reporter
Phosphorylation of 3' end was enough to block activity of RNAse T